spring.application.name=CarEase

# ============================
# LOCAL DATABASE (FOR ECLIPSE)
# ============================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/services?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root



# ============================
# JPA / Hibernate
# ============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ============================
# LOGGING
# ============================
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.springframework.security=OFF
logging.level.org.hibernate=ERROR
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=DEBUG

# ============================
# MAIL SETTINGS
# ============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=basawaprasad.b@gmail.com
spring.mail.password=ninj efay ecwq yddr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ============================
# RAZORPAY CONFIG
# ============================
razorpay.keyId=rzp_test_Rv5A6TezSAWIWD
razorpay.keySecret=Jf2mgxZUwFvnQR0dqJpSlDhl